### ISSUE TITLE
Determine whether ```recursive_helper``` in ```cky_tree``` is exponential time, and if so, then investigate a bottom-up alternative.

### ISSUE THREAD

**Issue by mhrmm** [Mark-Hopkins-at-Reed/bigsky#10]

**Comment by henlindemreed** [comment]
this is roughly linear in the number of words, but exponential in the number of ambiguities. By roughly linear I mean that there are in a binary tree exactly 2n-1 recursive calls, but depending on how many things any given node can be I will have to do some looping. So that means that a purely unambiguous sentence will take time to parse proportional to the number of things that were written down in the CKY table.
So yes, the recursive algorithm will perform poorly in situations where it has a lot of ambiguities to deal with, but I think that situations like that will be rare (at least for _this_ dataset); and otherwise, it does fine.
